# Generated by Django 4.1.1 on 2023-05-04 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 5, 0, 34, 10, 457678), editable=False)),
            ],
        ),
    ]
