# Generated by Django 4.1.1 on 2023-05-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_buyer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 0, 51, 8, 899535), editable=False),
        ),
    ]
