# Generated by Django 4.1.1 on 2023-05-10 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_messages_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 15, 28, 704815), editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_messages',
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 15, 28, 704815), editable=False),
        ),
    ]
