# Generated by Django 4.1.1 on 2023-05-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_message_delete_contact_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='status',
            field=models.CharField(default='Ready To Ship', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 42, 14, 325676), editable=False),
        ),
        migrations.AlterField(
            model_name='contact_message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 42, 14, 325676), editable=False),
        ),
    ]
